name: Sync Markdown and Excel Tables

on:
  push:
    paths:
      - README.md
      - tables/*.xlsx
  workflow_dispatch:

jobs:
  md_to_excel:
    if: contains(github.event.head_commit.modified, 'README.md')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas openpyxl
      - name: Ensure tables directory exists
        run: mkdir -p tables
      - name: Sync Markdown → Excel
        run: python .github/workflows/markdown_to_excel.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tables/
          git commit -m "Synced Excel tables from Markdown" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  excel_to_md:
    if: contains(github.event.head_commit.modified, 'tables/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas openpyxl
      - name: Sync Excel → Markdown
        run: python .github/workflows/excel_to_markdown.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Synced Markdown table from Excel" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
